#!/bin/bash
# init script for the openQRM development-plugin
#
# openQRM Enterprise developed by OPENQRM AUSTRALIA PTY LTD.
#
# All source code and content (c) Copyright 2021, OPENQRM AUSTRALIA PTY LTD unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with OPENQRM AUSTRALIA PTY LTD.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2021, OPENQRM AUSTRALIA PTY LTD <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/development/include/openqrm-plugin-development-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/development/etc/openqrm-plugin-development.conf
openqrm_server_get_config
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi


function openqrm_plugin_development_start() {
	echo "Starting the openQRM development-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/development/.running
}


function openqrm_plugin_development_stop() {
	echo "Stopping the openQRM development-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/development/.running
}

function openqrm_plugin_development_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "development: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "development: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM development-plugin"
	openqrm_plugin_development_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/development
}

function openqrm_plugin_development_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "development: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "development: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi

	echo "Initializing the openQRM development-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/development/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/development

}







USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_development_start
		;;
	stop)
		openqrm_plugin_development_stop
		;;
	restart)
		openqrm_plugin_development_stop
		sleep 1
		openqrm_plugin_development_start
		;;
	init)
		openqrm_plugin_development_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_development_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




