#!/bin/bash
# this is the boot-service init script for the Kvm-server hosts
#
# openQRM Enterprise developed by OPENQRM AUSTRALIA PTY LTD.
#
# All source code and content (c) Copyright 2021, OPENQRM AUSTRALIA PTY LTD unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with OPENQRM AUSTRALIA PTY LTD.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2021, OPENQRM AUSTRALIA PTY LTD <info@openqrm-enterprise.com>
#

export OPENQRM_SERVER_BASE_DIR=@@OPENQRM_SERVER_BASE_DIR@@
export OPENVSWITCH=@@OPENQRM_PLUGIN_KVM_BRIDGE@@
export PATH=/usr/sbin:/usr/bin:/sbin:/bin

# remove the tap dev
ifconfig $1 0.0.0.0 down
ovs-vsctl del-port ${OPENVSWITCH} $1

