configure:
compile:
install:
	mkdir -p /usr/share/openqrm/plugins/openvswitch-manager/etc
	cp etc/openqrm-plugin-openvswitch-manager.conf /usr/share/openqrm/plugins/openvswitch-manager/etc/
uninstall:
clean:
all:
