#!/bin/bash
# init script for the openQRM device-manager-plugin
#
# openQRM Enterprise developed by OPENQRM AUSTRALIA PTY LTD.
#
# All source code and content (c) Copyright 2021, OPENQRM AUSTRALIA PTY LTD unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with OPENQRM AUSTRALIA PTY LTD.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2021, OPENQRM AUSTRALIA PTY LTD <info@openqrm-enterprise.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/include/openqrm-plugin-device-manager-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/etc/openqrm-plugin-device-manager.conf
openqrm_server_get_config
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
	WGET_NO_CERT_CHECK="--no-check-certificate"
fi


function openqrm_plugin_device_manager_start() {
	echo "Starting the openQRM device-manager-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/device-manager/.running
}


function openqrm_plugin_device_manager_stop() {
	echo "Stopping the openQRM device-manager-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/device-manager/.running
}

function openqrm_plugin_device_manager_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "device-manager: Please give a username to uninstall the plugin : "
		read USERNAME
		echo
		echo -n "device-manager: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM device-manager-plugin"
	openqrm_plugin_device_manager_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-device-manager.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/device-manager
}

function openqrm_plugin_device_manager_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "device-manager: Please give a username to init the plugin : "
		read USERNAME
		echo
		echo -n "device-manager: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi

	echo "Initializing the openQRM device-manager-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/device-manager
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web/boot-service-device-manager.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-device-manager.tgz
	# create storage dir for stat files
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web/storage
	chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web/storage
	echo "Order deny,allow" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web/storage/.htaccess
	echo "Deny from all" >> $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/device-manager/web/storage/.htaccess

}







USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_device_manager_start
		;;
	stop)
		openqrm_plugin_device_manager_stop
		;;
	restart)
		openqrm_plugin_device_manager_stop
		sleep 1
		openqrm_plugin_device_manager_start
		;;
	init)
		openqrm_plugin_device_manager_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_device_manager_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




