configure:
compile:
install:
	mkdir -p /usr/share/openqrm/plugins/role-administration/etc
	cp etc/openqrm-plugin-role-administration.conf /usr/share/openqrm/plugins/role-administration/etc/
uninstall:
clean:
all:
