#!/bin/bash
# openQRM maintenance script, runs once a day via cron
#
# openQRM Enterprise developed by OPENQRM AUSTRALIA PTY LTD.
#
# All source code and content (c) Copyright 2021, OPENQRM AUSTRALIA PTY LTD unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with OPENQRM AUSTRALIA PTY LTD.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2021, OPENQRM AUSTRALIA PTY LTD <info@openqrm-enterprise.com>
#

. @@OPENQRM_SERVER_BASE_DIR@@/openqrm/etc/openqrm-server.conf
. @@OPENQRM_SERVER_BASE_DIR@@/openqrm/include/openqrm-server-functions
# get full server config
openqrm_server_get_config

# define maintenance dir for mysql backup files
DB_MAINTENANCE_DIR="/var/spool/openqrm_db/"


if ! which mysql 1>/dev/null 2>&1; then
	echo "ERROR: Mysql client 'mysql' not installed/found on this system" | logger
	exit 1
else
	export MYSQL_CLIENT=`which mysql`
fi
if ! which mysqldump 1>/dev/null 2>&1; then
	echo "ERROR: Mysql 'mysqldump' not installed/found on this system"  | logger
	exit 1
else
	export MYSQL_DUMP=`which mysqldump`
fi

BACKUP_TIME=`date +%T--%x | sed -e "s/:/-/g" | sed -e "s#/#-#g"`
if  [ "$OPENQRM_DATABASE_PASSWORD" != "" ]; then
	DB_PASS="-p$OPENQRM_DATABASE_PASSWORD"
fi

if [ ! -d "$DB_MAINTENANCE_DIR" ]; then
	mkdir -p $DB_MAINTENANCE_DIR
fi

# backup event_info table
echo "NOTICE: Saving event_info table to $DB_MAINTENANCE_DIR/openqrm_db_event_info_$BACKUP_TIME.sql"  | logger
$MYSQL_DUMP -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME event_info > $DB_MAINTENANCE_DIR/openqrm_db_event_info_$BACKUP_TIME.sql
gzip $DB_MAINTENANCE_DIR/openqrm_db_event_info_$BACKUP_TIME.sql
# clean up event_info table
echo "NOTICE: Cleaning event_info table"  | logger
$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "delete from event_info"
# clean up datacenter_info table
echo "NOTICE: Cleaning datacenter_info"  | logger
$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "delete from datacenter_info"

# backup cloud_transaction
if $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "show tables" | grep cloud_transaction 1>/dev/null; then
    echo "NOTICE: Saving cloud_transaction table to $DB_MAINTENANCE_DIR/openqrm_db_cloud_transaction_$BACKUP_TIME.sql"  | logger
    $MYSQL_DUMP -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME cloud_transaction > $DB_MAINTENANCE_DIR/openqrm_db_cloud_transaction_$BACKUP_TIME.sql
    gzip $DB_MAINTENANCE_DIR/openqrm_db_cloud_transaction_$BACKUP_TIME.sql
    # clean up cloud_transaction
    echo "NOTICE: Cleaning cloud_transaction table"  | logger
    $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "delete from cloud_transaction"
fi

# backup cloud_zones_transaction
if $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "show tables" | grep cloud_zones_transaction 1>/dev/null; then
    echo "NOTICE: Saving cloud_zones_transaction table to $DB_MAINTENANCE_DIR/openqrm_db_cloud_zones_transaction_$BACKUP_TIME.sql"  | logger
    $MYSQL_DUMP -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME cloud_zones_transaction > $DB_MAINTENANCE_DIR/openqrm_db_cloud_zones_transaction_$BACKUP_TIME.sql
    gzip $DB_MAINTENANCE_DIR/openqrm_db_cloud_zones_transaction_$BACKUP_TIME.sql
    # clean up cloud_zones_transaction
    echo "NOTICE: Cleaning cloud_zones_transaction table"  | logger
    $MYSQL_CLIENT -u $OPENQRM_DATABASE_USER $DB_PASS --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME -e "delete from cloud_zones_transaction"
fi

