configure:
compile:
install:
	mkdir -p /usr/share/openqrm/plugins/highavailability/etc
	cp etc/openqrm-plugin-highavailability.conf /usr/share/openqrm/plugins/highavailability/etc/
uninstall:
clean:
all:
