configure:
compile:
install:
	mkdir -p /usr/share/openqrm/plugins/sanboot-storage/etc
	cp etc/openqrm-plugin-sanboot-storage.conf /usr/share/openqrm/plugins/sanboot-storage/etc/
uninstall:
clean:
all:
