#!/bin/bash
# this is the functions file for the ansible-plugin
#
# openQRM Enterprise developed by OPENQRM AUSTRALIA PTY LTD.
#
# All source code and content (c) Copyright 2021, OPENQRM AUSTRALIA PTY LTD unless specifically noted otherwise.
#
# This source code is released under the GNU General Public License version 2, unless otherwise agreed with OPENQRM AUSTRALIA PTY LTD.
# The latest version of this license can be found here: src/doc/LICENSE.txt
#
# By using this software, you acknowledge having read this license and agree to be bound thereby.
#
#           http://openqrm-enterprise.com
#
# Copyright 2021, OPENQRM AUSTRALIA PTY LTD <info@openqrm-enterprise.com>
#

################ common ansible functions

# logs for ansible
function ansible_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "ansible plug-in" "$COMPONENT : $MESSAGE"
}





################ ansible functions






